### ISSUE TITLE
augment max number of replicates for control

### ISSUE THREAD

**Issue by proccaserra** [precisiontox/ptox-metadata-manager#123]
reported by @M-R-JONES 

context =  future exposure studies (8 controls vs 4 exposed at each time point, etc).
related to: https://docs.google.com/spreadsheets/d/1yd-E6HGjhGIdTRcIFpF4LqE5hxPN7g1F/edit#gid=1746580615
I encountered an error relating to too many controls.
Compound 999 is Control (DMSO). I set the number of control replicates to 8, but get an error message during validation stating that DAE999ZA5 is not valid, due to replicate number being 5 when only 4 allowed.
I believe this is a bug in the backend, where compound 999 needs to be recognised as a control type rather than an exposure compound?
000 = Control (water)
999 = Control (DMSO)
998 = blank

somehow related to #120

**Comment by M-R-JONES** [comment]
Just adding fresh doc link: https://docs.google.com/spreadsheets/d/1SboHblTb_Ngjr1aS5LHp2aXivKB10ny-/edit
