### ISSUE TITLE
validating regex triggered in 'Shipment identifier' if string start like a date

### ISSUE THREAD

**Issue by proccaserra** [precisiontox/ptox-metadata-manager#124]
reported by @M-R-JONES 

document: https://docs.google.com/spreadsheets/d/1yd-E6HGjhGIdTRcIFpF4LqE5hxPN7g1F/edit#gid=1746580615

description: "For column “shipment_identifier”, I received an error when I put a data in there, e.g. 2024-01-05.
Error message during validation: “Timestamp('2024-01-05 00:00:00') is not of type 'string'”
Honestly, I don't know if this is an issue per se, just wanted to flag up that entering a date-like entry caused an error...presumably Google autoformatted to date-time?".

"Related to the above, did we decide that we would demand that users set a shipment identifier BEFORE validating their metadata.
e.g. they've generated the skeleton, run their exposures and populated the spreadsheet with relevant info. At this point, I think it would be good to validate everything other than the shipment_identifier, as PCB would need to review and authorise shipment over to Birmingham. Once validated, the ship button becomes available (I think?). 

Could we have it that when they click the 'ship' button, that the validator then (re-)checks an entry was made in the shipment_identifier column?
sorry if I've forgotten some of the specifics here regarding validating once/twice, and when those are done. Just thought I'd make a note as I found it a little confusing to add a shipment ID before the 'ship' button was available.
I guess users could just set it to 'NA' to avoid any issues."

**Comment by terazus** [comment]
1. Is due to excel auto formatting the cell
2 and 3. Not doing, too complex.
