### ISSUE TITLE
swagger doc gives a 502 bad gateway error

### ISSUE THREAD

**Issue by proccaserra** [precisiontox/ptox-metadata-manager#163]
detected on 29.05.2024

**Comment by knirirr** [comment]
@proccaserra do you have any more information about this? E.g. whether this refers to a local installation or otherwise, how to reproduce etc. - thanks.

**Comment by proccaserra** [comment]
oh forgot about this, link updated to https://mmapi.precisiontox.org/apidocs/ via PR
