### ISSUE TITLE
hamburger on client shows unhelpful screen

### ISSUE THREAD

**Issue by proccaserra** [precisiontox/ptox-metadata-manager#21]
![image](https://user-images.githubusercontent.com/517736/215133843-530f5ea8-9168-4543-b7b4-834052e1a169.png)

**Comment by proccaserra** [comment]
on Chrome and Safari

**Comment by terazus** [comment]
Should be fixed now: 
![image](https://user-images.githubusercontent.com/6538906/216034473-2d506305-01b1-48fb-9b3d-5a3551b3c4d4.png)
