### ISSUE TITLE
UI: hide 'species_name' string under the main species label

### ISSUE THREAD

**Issue by proccaserra** [precisiontox/ptox-metadata-manager#54]
-[ ] option 1 - drop it from the UI entirely
-[ ] option 2 - in case it is functionally required, set the font-color to the same color as the background so not visible to users

**Comment by terazus** [comment]
See https://github.com/terazus/ptox-metadata-manager-client/tree/DomMajorUpdates


![Image](https://github.com/precisiontox/ptox-metadata-manager/assets/6538906/f889a0d9-91fa-4dac-8b47-edc2c60f3f8d)
![Image](https://github.com/precisiontox/ptox-metadata-manager/assets/6538906/01cd4222-c73e-4687-ad14-de4267582901)
![Image](https://github.com/precisiontox/ptox-metadata-manager/assets/6538906/e4583c39-c39f-4231-8266-54d6a72babd0)
