### ISSUE TITLE
Create precision-tox-manager account for each PT users

### ISSUE THREAD

**Issue by proccaserra** [precisiontox/ptox-metadata-manager#55]
For each partner {UoB, KIT, UoI, NIH, WTF, UFZ}
- [ ] check with each partner if more than one account is needed
- [ ] create an endpoint that, given a token, can create a new account and invalidate the token.
- [ ] send one token to each partner as a url

**Comment by terazus** [comment]
Not doing. Users can now register their own accounts which we will need to validate later.
