### ISSUE TITLE
User guidance in validation report

### ISSUE THREAD

**Issue by M-R-JONES** [precisiontox/ptox-metadata-manager#96]
Hi @terazus,

Would it be possible to provide users with more informative outputs for validation errors? e.g. instead of "box_row" is not string, we could say "'box_row' needs to be capitalised letter". Might be a challenge, so feel free to reject the idea.

![image](https://github.com/precisiontox/ptox-metadata-manager/assets/6332174/56ec3db4-8203-4f46-9ecb-7c1e46c3ddc0)

**Comment by terazus** [comment]
This is going to be hard as the validation is semi automatic. Meaning all types are verified through JSON schema and uses the library errors. JSON Schema first verifies the type, then verify the patterns.

This is the rule for the bow_row: https://github.com/precisiontox/ptox-metadata-manager/blob/main/ptmd/resources/schemas/exposure_information_sheet_schema.json#L21-L25
Would you pass a numerical value as a string "1" or an invalid value "ABC", then the type would match and the error raised would indicate you don't have the right pattern.

**Comment by M-R-JONES** [comment]
I think your suggestion is a good idea. The key aspect here is that the rules are followed and that the user can understand why they might not have complied with the rules through a user-friendly error message.
